// Emit the P25 voice-framing and IMBE/AMBE vocoder tables as Rust, from the
// archived TS engine's modules (which carry op25's and mbelib's numbers), so
// no table is ever transcribed by hand.
//
//   node --experimental-strip-types scripts/gen_tables.ts > crates/trunk-core/src/tables.rs

import * as voice from "../archive/ts-engine/src/vendor/ff/p25/voiceTables.ts";
import * as mbe from "../archive/ts-engine/src/vendor/ff/mbe/tables.ts";

const out: string[] = [
  "// GENERATED by scripts/gen_tables.ts — do not edit.",
  "// Voice framing: op25 op25_imbe_frame.h (GPLv3). Vocoder: mbelib (ISC; notice in",
  "// archive/ts-engine/src/vendor/ff/mbe/tables.ts).",
  "#![allow(clippy::all)]",
  "#![cfg_attr(rustfmt, rustfmt_skip)]",
  "",
];

function snake(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function emit(name: string, a: ArrayLike<number>) {
  const float = a instanceof Float32Array || a instanceof Float64Array;
  const type = float ? "f32" : a instanceof Int16Array ? "i16" : a instanceof Uint16Array ? "u16" : "i32";
  const vals = Array.from(a, (v) => (float ? (Number.isInteger(v) ? `${v}.0` : `${Math.fround(v)}`) : String(v)));
  const lines: string[] = [];
  for (let i = 0; i < vals.length; i += 16) lines.push("    " + vals.slice(i, i + 16).join(", ") + ",");
  out.push(`pub static ${snake(name)}: [${type}; ${vals.length}] = [`, ...lines, "];", "");
}

for (const mod of [voice, mbe]) {
  for (const [k, v] of Object.entries(mod)) {
    if (ArrayBuffer.isView(v)) emit(k, v as unknown as ArrayLike<number>);
  }
}
console.log(out.join("\n"));
