// Emit the P25 voice-framing and IMBE/AMBE vocoder tables as Rust, from the
// archived TS engine's modules (which carry op25's and mbelib's numbers), so
// no table is ever transcribed by hand.
//
//   node --experimental-strip-types scripts/gen_tables.ts > crates/trunk-core/src/tables.rs

import * as voice from "../archive/ts-engine/src/vendor/ff/p25/voiceTables.ts";
import * as mbe from "../archive/ts-engine/src/vendor/ff/mbe/tables.ts";
import * as p2 from "../archive/ts-engine/src/vendor/ff/p25/phase2Tables.ts";

const out: string[] = [
  "// GENERATED by scripts/gen_tables.ts — do not edit.",
  "// Voice framing: op25 op25_imbe_frame.h (GPLv3). Vocoder: mbelib (ISC; notice in",
  "// archive/ts-engine/src/vendor/ff/mbe/tables.ts). Phase 2: op25 p25p2_isch.cc,",
  "// p25p2_duid.cc, apps/tdma/lfsr.py (GPLv3).",
  "#![allow(clippy::all)]",
  "#![cfg_attr(rustfmt, rustfmt_skip)]",
  "",
];

function snake(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function emit(name: string, a: ArrayLike<number>) {
  const float = a instanceof Float32Array || a instanceof Float64Array;
  const type = float ? "f32" : a instanceof Int8Array ? "i8" : a instanceof Int16Array ? "i16" : a instanceof Uint16Array ? "u16" : "i32";
  const vals = Array.from(a, (v) => (float ? (Number.isInteger(v) ? `${v}.0` : `${Math.fround(v)}`) : String(v)));
  const lines: string[] = [];
  for (let i = 0; i < vals.length; i += 16) lines.push("    " + vals.slice(i, i + 16).join(", ") + ",");
  out.push(`pub static ${snake(name)}: [${type}; ${vals.length}] = [`, ...lines, "];", "");
}

for (const mod of [voice, mbe]) {
  for (const [k, v] of Object.entries(mod)) {
    if (k === "DUID_LOOKUP") continue; // below
    if (ArrayBuffer.isView(v)) emit(k, v as unknown as ArrayLike<number>);
  }
}
// Phase 2 TDMA.
emit("DUID_LOOKUP", p2.DUID_LOOKUP);
out.push("/// (40-bit codeword, value): I-ISCH values 0..127, the S-ISCH sync word −2.");
out.push(`pub static ISCH_CODEWORDS: [(u64, i8); ${p2.ISCH_CODEWORDS.length}] = [`);
for (const [hex, v] of p2.ISCH_CODEWORDS) out.push(`    (0x${hex}, ${v}),`);
out.push("];", "");
out.push("/// Scrambler seed matrix rows (44 × 44 over GF(2)); bit 43 is column 0.");
out.push(`pub static LFSR_SEED_MATRIX: [u64; ${p2.LFSR_SEED_MATRIX.length}] = [`);
for (const row of p2.LFSR_SEED_MATRIX) out.push(`    0b${row},`);
out.push("];", "");
console.log(out.join("\n"));
